import { Sun, Moon, Bed, Utensils, Plane, Heart, Home, BookOpen, Droplets, Shield, Baby, Stethoscope, Users, Sparkles, Clock, MapPin, Shirt, DoorOpen, Car, Umbrella, Cloud, Eye, HandHeart, type LucideIcon } from 'lucide-react';

export interface DuaItem {
  id: number;
  category: string;
  categoryBn: string;
  title: string;
  titleBn: string;
  arabic: string;
  transliteration: string;
  translation: string;
  translationBn: string;
  reference: string;
  icon: LucideIcon;
}

export interface DuaCategory {
  id: string;
  label: string;
  labelBn: string;
  icon: LucideIcon;
  color: string;
}

export const duaCategories: DuaCategory[] = [
  { id: 'all', label: 'All', labelBn: 'সব', icon: HandHeart, color: 'bg-primary/10 text-primary' },
  { id: 'morning', label: 'Morning', labelBn: 'সকাল', icon: Sun, color: 'bg-amber-500/10 text-amber-600' },
  { id: 'evening', label: 'Evening', labelBn: 'সন্ধ্যা', icon: Moon, color: 'bg-indigo-500/10 text-indigo-600' },
  { id: 'sleep', label: 'Sleep', labelBn: 'ঘুম', icon: Bed, color: 'bg-purple-500/10 text-purple-600' },
  { id: 'food', label: 'Food', labelBn: 'খাওয়া', icon: Utensils, color: 'bg-orange-500/10 text-orange-600' },
  { id: 'travel', label: 'Travel', labelBn: 'ভ্রমণ', icon: Plane, color: 'bg-sky-500/10 text-sky-600' },
  { id: 'prayer', label: 'Prayer', labelBn: 'নামাজ', icon: BookOpen, color: 'bg-emerald-500/10 text-emerald-600' },
  { id: 'home', label: 'Home', labelBn: 'ঘর', icon: Home, color: 'bg-rose-500/10 text-rose-600' },
  { id: 'protection', label: 'Protection', labelBn: 'সুরক্ষা', icon: Shield, color: 'bg-red-500/10 text-red-600' },
  { id: 'health', label: 'Health', labelBn: 'স্বাস্থ্য', icon: Stethoscope, color: 'bg-teal-500/10 text-teal-600' },
  { id: 'family', label: 'Family', labelBn: 'পরিবার', icon: Users, color: 'bg-pink-500/10 text-pink-600' },
  { id: 'forgiveness', label: 'Forgiveness', labelBn: 'ক্ষমা', icon: Sparkles, color: 'bg-violet-500/10 text-violet-600' },
  { id: 'general', label: 'General', labelBn: 'সাধারণ', icon: Heart, color: 'bg-green-500/10 text-green-600' },
];

export const duas: DuaItem[] = [
  // === MORNING DUAS (1-10) ===
  {
    id: 1,
    category: 'morning',
    categoryBn: 'সকাল',
    title: 'Morning Supplication',
    titleBn: 'সকালের দোয়া',
    arabic: 'أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ',
    transliteration: "Asbahna wa asbahal mulku lillah, walhamdu lillah, la ilaha illallahu wahdahu la shareeka lah",
    translation: 'We have reached the morning and at this very time unto Allah belongs all sovereignty, and all praise is for Allah.',
    translationBn: 'আমরা সকালে উপনীত হয়েছি এবং এই সময়ে সকল সার্বভৌমত্ব আল্লাহর, সকল প্রশংসা আল্লাহর।',
    reference: 'Abu Dawud',
    icon: Sun,
  },
  {
    id: 2,
    category: 'morning',
    categoryBn: 'সকাল',
    title: 'Seeking Protection in Morning',
    titleBn: 'সকালে সুরক্ষা চাওয়া',
    arabic: 'اللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ النُّشُورُ',
    transliteration: "Allahumma bika asbahna, wa bika amsayna, wa bika nahya, wa bika namootu, wa ilaykan-nushoor",
    translation: 'O Allah, by Your leave we have reached the morning and by Your leave we have reached the evening, by Your leave we live and die and unto You is our return.',
    translationBn: 'হে আল্লাহ! তোমার অনুমতিতে আমরা সকালে উপনীত হয়েছি, তোমার অনুমতিতে আমরা বাঁচি ও মরি এবং তোমার কাছেই আমাদের প্রত্যাবর্তন।',
    reference: 'Tirmidhi',
    icon: Sun,
  },
  {
    id: 3,
    category: 'morning',
    categoryBn: 'সকাল',
    title: 'Master of Seeking Forgiveness',
    titleBn: 'ক্ষমা চাওয়ার সর্বোত্তম দোয়া',
    arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ خَلَقْتَنِي وَأَنَا عَبْدُكَ وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ',
    transliteration: "Allahumma anta Rabbi la ilaha illa anta, khalaqtani wa ana abduka, wa ana ala ahdika wa wadika mastata'tu",
    translation: 'O Allah, You are my Lord, none has the right to be worshipped except You, You created me and I am Your servant.',
    translationBn: 'হে আল্লাহ! তুমি আমার প্রতিপালক। তুমি ছাড়া কোনো উপাস্য নেই। তুমি আমাকে সৃষ্টি করেছ এবং আমি তোমার দাস।',
    reference: 'Sahih Bukhari',
    icon: Sun,
  },
  {
    id: 4,
    category: 'morning',
    categoryBn: 'সকাল',
    title: 'Gratitude for Waking Up',
    titleBn: 'জেগে ওঠার জন্য কৃতজ্ঞতা',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ',
    transliteration: "Alhamdu lillahil-ladhi ahyana ba'da ma amatana wa ilayhin-nushoor",
    translation: 'All praise is for Allah who gave us life after having taken it from us and unto Him is the resurrection.',
    translationBn: 'সকল প্রশংসা আল্লাহর যিনি আমাদের মৃত্যুর পর জীবিত করেছেন এবং তাঁর কাছেই পুনরুত্থান।',
    reference: 'Sahih Bukhari',
    icon: Sun,
  },
  {
    id: 5,
    category: 'morning',
    categoryBn: 'সকাল',
    title: 'Morning Protection from Evil',
    titleBn: 'সকালে মন্দ থেকে সুরক্ষা',
    arabic: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ',
    transliteration: "A'udhu bikalimaat-illahit-tammaati min sharri ma khalaq",
    translation: 'I seek refuge in the perfect words of Allah from the evil of what He has created.',
    translationBn: 'আমি আল্লাহর পরিপূর্ণ কালামের মাধ্যমে তাঁর সৃষ্টির সকল অনিষ্ট থেকে আশ্রয় চাই।',
    reference: 'Muslim',
    icon: Sun,
  },
  {
    id: 6,
    category: 'morning',
    categoryBn: 'সকাল',
    title: 'Contentment with Allah',
    titleBn: 'আল্লাহর প্রতি সন্তুষ্টি',
    arabic: 'رَضِيتُ بِاللَّهِ رَبًّا، وَبِالْإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ نَبِيًّا',
    transliteration: "Radheetu billahi rabban, wa bil-islami deenan, wa bi-Muhammadin sallallahu alayhi wa sallama nabiyya",
    translation: 'I am pleased with Allah as a Lord, and Islam as a religion and Muhammad (peace be upon him) as a Prophet.',
    translationBn: 'আমি আল্লাহকে প্রতিপালক, ইসলামকে দ্বীন এবং মুহাম্মদ (সা.) কে নবী হিসেবে সন্তুষ্টচিত্তে গ্রহণ করেছি।',
    reference: 'Abu Dawud',
    icon: Sun,
  },
  {
    id: 7,
    category: 'morning',
    categoryBn: 'সকাল',
    title: 'For a Blessed Day',
    titleBn: 'বরকতময় দিনের জন্য',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَ هَذَا الْيَوْمِ فَتْحَهُ وَنَصْرَهُ وَنُورَهُ وَبَرَكَتَهُ وَهُدَاهُ',
    transliteration: "Allahumma inni as'aluka khayra hadhal-yawmi fathahu wa nasrahu wa nurahu wa barakatahu wa hudahu",
    translation: 'O Allah, I ask You for the good of this day, its opening, its help, its light, its blessing and its guidance.',
    translationBn: 'হে আল্লাহ! আমি এই দিনের কল্যাণ, সাফল্য, সাহায্য, আলো, বরকত ও হেদায়াত চাই।',
    reference: 'Abu Dawud',
    icon: Sun,
  },
  {
    id: 8,
    category: 'morning',
    categoryBn: 'সকাল',
    title: 'Seeking Good Health',
    titleBn: 'সুস্বাস্থ্য কামনা',
    arabic: 'اللَّهُمَّ عَافِنِي فِي بَدَنِي، اللَّهُمَّ عَافِنِي فِي سَمْعِي، اللَّهُمَّ عَافِنِي فِي بَصَرِي',
    transliteration: "Allahumma 'afini fi badani, Allahumma 'afini fi sam'i, Allahumma 'afini fi basari",
    translation: 'O Allah, grant my body health, O Allah, grant my hearing health, O Allah, grant my sight health.',
    translationBn: 'হে আল্লাহ! আমার শরীরে সুস্থতা দাও, আমার শ্রবণে সুস্থতা দাও, আমার দৃষ্টিতে সুস্থতা দাও।',
    reference: 'Abu Dawud',
    icon: Sun,
  },
  
  // === EVENING DUAS (9-18) ===
  {
    id: 9,
    category: 'evening',
    categoryBn: 'সন্ধ্যা',
    title: 'Evening Supplication',
    titleBn: 'সন্ধ্যার দোয়া',
    arabic: 'أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ',
    transliteration: "Amsayna wa amsal mulku lillah, walhamdu lillah, la ilaha illallahu wahdahu la shareeka lah",
    translation: 'We have reached the evening and at this very time unto Allah belongs all sovereignty, and all praise is for Allah.',
    translationBn: 'আমরা সন্ধ্যায় উপনীত হয়েছি এবং এই সময়ে সকল সার্বভৌমত্ব আল্লাহর, সকল প্রশংসা আল্লাহর।',
    reference: 'Abu Dawud',
    icon: Moon,
  },
  {
    id: 10,
    category: 'evening',
    categoryBn: 'সন্ধ্যা',
    title: 'Seeking Protection in Evening',
    titleBn: 'সন্ধ্যায় সুরক্ষা চাওয়া',
    arabic: 'اللَّهُمَّ بِكَ أَمْسَيْنَا، وَبِكَ أَصْبَحْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ الْمَصِيرُ',
    transliteration: "Allahumma bika amsayna, wa bika asbahna, wa bika nahya, wa bika namootu, wa ilaykal-maseer",
    translation: 'O Allah, by Your leave we have reached the evening and by Your leave we have reached the morning, by Your leave we live and die and unto You is our final destination.',
    translationBn: 'হে আল্লাহ! তোমার অনুমতিতে আমরা সন্ধ্যায় উপনীত হয়েছি, তোমার অনুমতিতে আমরা বাঁচি ও মরি এবং তোমার কাছেই আমাদের প্রত্যাবর্তন।',
    reference: 'Tirmidhi',
    icon: Moon,
  },
  {
    id: 11,
    category: 'evening',
    categoryBn: 'সন্ধ্যা',
    title: 'Evening Protection',
    titleBn: 'সন্ধ্যায় হেফাজত',
    arabic: 'اللَّهُمَّ مَا أَمْسَى بِي مِنْ نِعْمَةٍ أَوْ بِأَحَدٍ مِنْ خَلْقِكَ فَمِنْكَ وَحْدَكَ لَا شَرِيكَ لَكَ',
    transliteration: "Allahumma ma amsa bi min ni'matin aw bi-ahadin min khalqik, faminka wahdak, la shareeka lak",
    translation: 'O Allah, what blessing I or any of Your creation have this evening is from You alone, no partner have You.',
    translationBn: 'হে আল্লাহ! এই সন্ধ্যায় আমি বা তোমার সৃষ্টির কেউ যে নেয়ামত পেয়েছি তা শুধুমাত্র তোমার পক্ষ থেকে, তোমার কোনো শরীক নেই।',
    reference: 'Abu Dawud',
    icon: Moon,
  },
  {
    id: 12,
    category: 'evening',
    categoryBn: 'সন্ধ্যা',
    title: 'Seeking Refuge at Night',
    titleBn: 'রাতে আশ্রয় প্রার্থনা',
    arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْكُفْرِ وَالْفَقْرِ، اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ عَذَابِ الْقَبْرِ',
    transliteration: "Allahumma inni a'udhu bika minal-kufri wal-faqr, Allahumma inni a'udhu bika min adhabil-qabr",
    translation: 'O Allah, I seek refuge in You from disbelief and poverty. O Allah, I seek refuge in You from the punishment of the grave.',
    translationBn: 'হে আল্লাহ! আমি কুফর ও দারিদ্র্য থেকে তোমার কাছে আশ্রয় চাই। হে আল্লাহ! আমি কবরের আযাব থেকে তোমার কাছে আশ্রয় চাই।',
    reference: 'Abu Dawud',
    icon: Moon,
  },
  {
    id: 13,
    category: 'evening',
    categoryBn: 'সন্ধ্যা',
    title: 'For a Peaceful Night',
    titleBn: 'শান্তিপূর্ণ রাতের জন্য',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَ هَذِهِ اللَّيْلَةِ وَأَعُوذُ بِكَ مِنْ شَرِّ هَذِهِ اللَّيْلَةِ',
    transliteration: "Allahumma inni as'aluka khayra hadhihil-laylah wa a'udhu bika min sharri hadhihil-laylah",
    translation: 'O Allah, I ask You for the good of this night and I seek refuge in You from the evil of this night.',
    translationBn: 'হে আল্লাহ! আমি এই রাতের কল্যাণ চাই এবং এই রাতের অনিষ্ট থেকে আশ্রয় চাই।',
    reference: 'Abu Dawud',
    icon: Moon,
  },

  // === SLEEP DUAS (14-23) ===
  {
    id: 14,
    category: 'sleep',
    categoryBn: 'ঘুম',
    title: 'Before Sleeping',
    titleBn: 'ঘুমানোর আগে',
    arabic: 'بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا',
    transliteration: "Bismika Allahumma amootu wa ahya",
    translation: 'In Your name, O Allah, I die and I live.',
    translationBn: 'হে আল্লাহ, তোমার নামে আমি মারা যাই এবং জীবিত হই।',
    reference: 'Sahih Bukhari',
    icon: Bed,
  },
  {
    id: 15,
    category: 'sleep',
    categoryBn: 'ঘুম',
    title: 'Entrusting Oneself to Allah',
    titleBn: 'আল্লাহর উপর ভরসা',
    arabic: 'اللَّهُمَّ أَسْلَمْتُ نَفْسِي إِلَيْكَ، وَفَوَّضْتُ أَمْرِي إِلَيْكَ، وَوَجَّهْتُ وَجْهِي إِلَيْكَ',
    transliteration: "Allahumma aslamtu nafsi ilayk, wa fawwadtu amri ilayk, wa wajjahtu wajhi ilayk",
    translation: 'O Allah, I submit myself to You, entrust my affairs to You, and turn my face towards You.',
    translationBn: 'হে আল্লাহ! আমি নিজেকে তোমার কাছে সমর্পণ করলাম, আমার সকল বিষয় তোমার উপর ন্যস্ত করলাম এবং তোমার দিকে মুখ ফেরালাম।',
    reference: 'Sahih Bukhari',
    icon: Bed,
  },
  {
    id: 16,
    category: 'sleep',
    categoryBn: 'ঘুম',
    title: 'Protection During Sleep',
    titleBn: 'ঘুমের সময় সুরক্ষা',
    arabic: 'اللَّهُمَّ قِنِي عَذَابَكَ يَوْمَ تَبْعَثُ عِبَادَكَ',
    transliteration: "Allahumma qini adhabaka yawma tab'athu ibadak",
    translation: 'O Allah, protect me from Your punishment on the Day You resurrect Your servants.',
    translationBn: 'হে আল্লাহ! যেদিন তুমি তোমার বান্দাদের পুনরুত্থিত করবে সেদিন তোমার শাস্তি থেকে আমাকে রক্ষা কর।',
    reference: 'Abu Dawud',
    icon: Bed,
  },
  {
    id: 17,
    category: 'sleep',
    categoryBn: 'ঘুম',
    title: 'When Waking at Night',
    titleBn: 'রাতে জেগে উঠলে',
    arabic: 'لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
    transliteration: "La ilaha illallahu wahdahu la shareeka lah, lahul-mulku wa lahul-hamd, wa huwa ala kulli shay'in qadeer",
    translation: 'None has the right to be worshipped except Allah, alone without partner, to Him belongs all sovereignty and praise and He is over all things omnipotent.',
    translationBn: 'আল্লাহ ছাড়া কোনো উপাস্য নেই, তিনি একক, তাঁর কোনো শরীক নেই। রাজত্ব তাঁরই এবং সকল প্রশংসা তাঁর এবং তিনি সবকিছুর উপর সর্বশক্তিমান।',
    reference: 'Sahih Bukhari',
    icon: Bed,
  },
  {
    id: 18,
    category: 'sleep',
    categoryBn: 'ঘুম',
    title: 'After Having a Bad Dream',
    titleBn: 'দুঃস্বপ্নের পর',
    arabic: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ غَضَبِهِ وَعِقَابِهِ وَشَرِّ عِبَادِهِ',
    transliteration: "A'udhu bi kalimatillahit-tammati min ghadabihi wa iqabihi wa sharri ibadihi",
    translation: 'I seek refuge in the perfect words of Allah from His anger, His punishment, and the evil of His servants.',
    translationBn: 'আমি আল্লাহর পরিপূর্ণ কালামের মাধ্যমে তাঁর ক্রোধ, তাঁর শাস্তি এবং তাঁর বান্দাদের অনিষ্ট থেকে আশ্রয় চাই।',
    reference: 'Abu Dawud',
    icon: Bed,
  },
  {
    id: 19,
    category: 'sleep',
    categoryBn: 'ঘুম',
    title: 'When Having Insomnia',
    titleBn: 'ঘুম না আসলে',
    arabic: 'اللَّهُمَّ غَارَتِ النُّجُومُ، وَهَدَأَتِ الْعُيُونُ، وَأَنْتَ حَيٌّ قَيُّومٌ، يَا حَيُّ يَا قَيُّومُ أَهْدِئْ لَيْلِي',
    transliteration: "Allahumma ghaaratinnujum, wa hada'atil-uyun, wa anta Hayyun Qayyum, ya Hayyu ya Qayyum ahdi' layli",
    translation: 'O Allah, the stars have gone far away and the eyes are rested. You are the Ever Living, the One Who sustains all that exists. O Ever Living, O One Who sustains, give rest to my night.',
    translationBn: 'হে আল্লাহ! তারারা অস্তমিত হয়েছে, চোখগুলো বিশ্রাম নিচ্ছে। তুমি চিরঞ্জীব, সর্বসত্তার ধারক। হে চিরঞ্জীব! আমার রাতকে শান্তি দাও।',
    reference: 'Ibn Sunni',
    icon: Bed,
  },

  // === FOOD DUAS (20-28) ===
  {
    id: 20,
    category: 'food',
    categoryBn: 'খাওয়া',
    title: 'Before Eating',
    titleBn: 'খাওয়ার আগে',
    arabic: 'بِسْمِ اللَّهِ وَعَلَى بَرَكَةِ اللَّهِ',
    transliteration: "Bismillahi wa ala barakatillah",
    translation: 'In the name of Allah and with the blessings of Allah.',
    translationBn: 'আল্লাহর নামে এবং আল্লাহর বরকতে।',
    reference: 'Abu Dawud',
    icon: Utensils,
  },
  {
    id: 21,
    category: 'food',
    categoryBn: 'খাওয়া',
    title: 'After Eating',
    titleBn: 'খাওয়ার পরে',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ',
    transliteration: "Alhamdu lillahil-ladhi at'amana wa saqana wa ja'alana muslimeen",
    translation: 'All praise is for Allah who fed us, gave us drink, and made us Muslims.',
    translationBn: 'সকল প্রশংসা আল্লাহর যিনি আমাদের খাওয়ালেন, পান করালেন এবং মুসলিম বানালেন।',
    reference: 'Abu Dawud',
    icon: Utensils,
  },
  {
    id: 22,
    category: 'food',
    categoryBn: 'খাওয়া',
    title: 'Gratitude for Food',
    titleBn: 'খাবারের জন্য কৃতজ্ঞতা',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي هَذَا، وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ',
    transliteration: "Alhamdu lillahil-ladhi at'amani hadha, wa razaqaneehi min ghayri hawlin minni wa la quwwah",
    translation: 'All praise is for Allah who fed me this and provided it for me without any might or power from myself.',
    translationBn: 'সকল প্রশংসা আল্লাহর যিনি আমাকে এটা খাওয়ালেন এবং আমার কোনো শক্তি বা সামর্থ্য ছাড়াই এটা আমাকে দান করলেন।',
    reference: 'Abu Dawud',
    icon: Utensils,
  },
  {
    id: 23,
    category: 'food',
    categoryBn: 'খাওয়া',
    title: 'If Forgot to Say Bismillah',
    titleBn: 'বিসমিল্লাহ বলতে ভুলে গেলে',
    arabic: 'بِسْمِ اللَّهِ أَوَّلَهُ وَآخِرَهُ',
    transliteration: "Bismillahi awwalahu wa akhirah",
    translation: 'In the name of Allah at the beginning and at the end.',
    translationBn: 'আল্লাহর নামে এর শুরু ও শেষে।',
    reference: 'Abu Dawud',
    icon: Utensils,
  },
  {
    id: 24,
    category: 'food',
    categoryBn: 'খাওয়া',
    title: 'When Breaking Fast',
    titleBn: 'ইফতারের সময়',
    arabic: 'ذَهَبَ الظَّمَأُ وَابْتَلَّتِ الْعُرُوقُ وَثَبَتَ الْأَجْرُ إِنْ شَاءَ اللَّهُ',
    transliteration: "Dhahaba zama'u wabtallatil-urooq, wa thabatal-ajru insha'Allah",
    translation: 'The thirst has gone, the veins are moistened, and the reward is confirmed, if Allah wills.',
    translationBn: 'তৃষ্ণা দূর হয়েছে, শিরা-উপশিরা সিক্ত হয়েছে এবং আল্লাহ চাইলে সওয়াব নিশ্চিত হয়েছে।',
    reference: 'Abu Dawud',
    icon: Utensils,
  },
  {
    id: 25,
    category: 'food',
    categoryBn: 'খাওয়া',
    title: 'Before Drinking Milk',
    titleBn: 'দুধ পানের আগে',
    arabic: 'اللَّهُمَّ بَارِكْ لَنَا فِيهِ وَزِدْنَا مِنْهُ',
    transliteration: "Allahumma barik lana fihi wa zidna minh",
    translation: 'O Allah, bless it for us and give us more of it.',
    translationBn: 'হে আল্লাহ! আমাদের জন্য এতে বরকত দাও এবং আমাদের আরও দাও।',
    reference: 'Tirmidhi',
    icon: Utensils,
  },
  {
    id: 26,
    category: 'food',
    categoryBn: 'খাওয়া',
    title: 'When Guest Finishes Eating',
    titleBn: 'মেহমানের খাওয়া শেষে',
    arabic: 'اللَّهُمَّ أَطْعِمْ مَنْ أَطْعَمَنِي، وَاسْقِ مَنْ سَقَانِي',
    transliteration: "Allahumma at'im man at'amani, wasqi man saqani",
    translation: 'O Allah, feed the one who fed me, and give drink to the one who gave me drink.',
    translationBn: 'হে আল্লাহ! যে আমাকে খাইয়েছে তাকে খাওয়াও এবং যে আমাকে পান করিয়েছে তাকে পান করাও।',
    reference: 'Muslim',
    icon: Utensils,
  },

  // === TRAVEL DUAS (27-35) ===
  {
    id: 27,
    category: 'travel',
    categoryBn: 'ভ্রমণ',
    title: 'When Starting a Journey',
    titleBn: 'ভ্রমণ শুরুর সময়',
    arabic: 'سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ',
    transliteration: "Subhanal-ladhi sakh-khara lana hadha wa ma kunna lahu muqrinin, wa inna ila Rabbina lamunqaliboon",
    translation: 'Glory unto Him Who created this transportation for us though we were unable to create it on our own. And unto our Lord we shall return.',
    translationBn: 'পবিত্র সেই সত্তা যিনি এটি আমাদের অধীন করে দিয়েছেন, অথচ আমরা একে বশ করতে সক্ষম ছিলাম না। এবং আমরা অবশ্যই আমাদের প্রতিপালকের কাছে ফিরে যাব।',
    reference: 'Quran 43:13-14',
    icon: Plane,
  },
  {
    id: 28,
    category: 'travel',
    categoryBn: 'ভ্রমণ',
    title: 'Travel Prayer',
    titleBn: 'সফরের দোয়া',
    arabic: 'اللَّهُمَّ إِنَّا نَسْأَلُكَ فِي سَفَرِنَا هَذَا الْبِرَّ وَالتَّقْوَى، وَمِنَ الْعَمَلِ مَا تَرْضَى',
    transliteration: "Allahumma inna nas'aluka fi safarina hadhal-birra wat-taqwa, wa minal-amali ma tarda",
    translation: 'O Allah, we ask You on this our journey for goodness and piety, and for works that are pleasing to You.',
    translationBn: 'হে আল্লাহ! আমরা এই সফরে তোমার কাছে পুণ্য ও তাকওয়া চাই এবং এমন আমল চাই যা তোমার সন্তুষ্টির কারণ হয়।',
    reference: 'Muslim',
    icon: Plane,
  },
  {
    id: 29,
    category: 'travel',
    categoryBn: 'ভ্রমণ',
    title: 'When Entering a Vehicle',
    titleBn: 'গাড়িতে উঠার সময়',
    arabic: 'بِسْمِ اللَّهِ، الْحَمْدُ لِلَّهِ، سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ',
    transliteration: "Bismillah, Alhamdulillah, Subhanal-ladhi sakh-khara lana hadha wa ma kunna lahu muqrinin",
    translation: 'In the name of Allah. All praise is for Allah. Glory unto Him Who created this for us though we were unable.',
    translationBn: 'আল্লাহর নামে। সকল প্রশংসা আল্লাহর। পবিত্র সেই সত্তা যিনি এটি আমাদের অধীন করে দিয়েছেন অথচ আমরা সক্ষম ছিলাম না।',
    reference: 'Abu Dawud',
    icon: Car,
  },
  {
    id: 30,
    category: 'travel',
    categoryBn: 'ভ্রমণ',
    title: 'When Returning from Travel',
    titleBn: 'সফর থেকে ফিরে',
    arabic: 'آيِبُونَ تَائِبُونَ عَابِدُونَ لِرَبِّنَا حَامِدُونَ',
    transliteration: "Ayiboona, ta'iboona, aabidoona, li Rabbina hamidoon",
    translation: 'We return, repent, worship and praise our Lord.',
    translationBn: 'আমরা প্রত্যাবর্তনকারী, তওবাকারী, ইবাদতকারী এবং আমাদের রবের প্রশংসাকারী।',
    reference: 'Muslim',
    icon: Plane,
  },
  {
    id: 31,
    category: 'travel',
    categoryBn: 'ভ্রমণ',
    title: 'When Entering a Town',
    titleBn: 'শহরে প্রবেশকালে',
    arabic: 'اللَّهُمَّ رَبَّ السَّمَاوَاتِ السَّبْعِ وَمَا أَظْلَلْنَ، وَرَبَّ الْأَرَضِينَ السَّبْعِ وَمَا أَقْلَلْنَ',
    transliteration: "Allahumma Rabbas-samawatis-sab'i wa ma adhlalna, wa Rabbal-aradeen as-sab'i wa ma aqlaln",
    translation: 'O Allah, Lord of the seven heavens and all that they envelop, Lord of the seven earths and all that they carry.',
    translationBn: 'হে আল্লাহ! সাত আসমান ও এর নিচে যা আছে তার প্রতিপালক, সাত জমিন ও এর উপরে যা আছে তার প্রতিপালক।',
    reference: 'Hakim',
    icon: MapPin,
  },
  {
    id: 32,
    category: 'travel',
    categoryBn: 'ভ্রমণ',
    title: 'When Ascending',
    titleBn: 'উপরে উঠার সময়',
    arabic: 'اللَّهُ أَكْبَرُ',
    transliteration: "Allahu Akbar",
    translation: 'Allah is the Greatest.',
    translationBn: 'আল্লাহ সবচেয়ে বড়।',
    reference: 'Sahih Bukhari',
    icon: Plane,
  },
  {
    id: 33,
    category: 'travel',
    categoryBn: 'ভ্রমণ',
    title: 'When Descending',
    titleBn: 'নিচে নামার সময়',
    arabic: 'سُبْحَانَ اللَّهِ',
    transliteration: "Subhanallah",
    translation: 'Glory be to Allah.',
    translationBn: 'আল্লাহ পবিত্র।',
    reference: 'Sahih Bukhari',
    icon: Plane,
  },

  // === PRAYER DUAS (34-43) ===
  {
    id: 34,
    category: 'prayer',
    categoryBn: 'নামাজ',
    title: 'Opening Supplication',
    titleBn: 'সানা',
    arabic: 'سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ، وَتَبَارَكَ اسْمُكَ، وَتَعَالَى جَدُّكَ، وَلَا إِلَهَ غَيْرُكَ',
    transliteration: "Subhanakallahumma wa bihamdik, wa tabarakasmuk, wa ta'ala jadduk, wa la ilaha ghayruk",
    translation: 'Glory be to You O Allah and praise. Blessed is Your name and exalted is Your majesty. There is no god but You.',
    translationBn: 'হে আল্লাহ! তুমি পবিত্র ও প্রশংসিত। তোমার নাম বরকতময়, তোমার মর্যাদা সুউচ্চ এবং তুমি ছাড়া কোনো উপাস্য নেই।',
    reference: 'Abu Dawud',
    icon: BookOpen,
  },
  {
    id: 35,
    category: 'prayer',
    categoryBn: 'নামাজ',
    title: 'In Ruku (Bowing)',
    titleBn: 'রুকুতে',
    arabic: 'سُبْحَانَ رَبِّيَ الْعَظِيمِ',
    transliteration: "Subhana Rabbiyal-Adheem",
    translation: 'Glory be to my Lord, the Almighty.',
    translationBn: 'আমার মহান প্রতিপালক পবিত্র।',
    reference: 'Muslim',
    icon: BookOpen,
  },
  {
    id: 36,
    category: 'prayer',
    categoryBn: 'নামাজ',
    title: 'In Sujud (Prostration)',
    titleBn: 'সিজদায়',
    arabic: 'سُبْحَانَ رَبِّيَ الْأَعْلَى',
    transliteration: "Subhana Rabbiyal-A'la",
    translation: 'Glory be to my Lord, the Most High.',
    translationBn: 'আমার সুমহান প্রতিপালক পবিত্র।',
    reference: 'Muslim',
    icon: BookOpen,
  },
  {
    id: 37,
    category: 'prayer',
    categoryBn: 'নামাজ',
    title: 'Between Two Sujud',
    titleBn: 'দুই সিজদার মাঝে',
    arabic: 'رَبِّ اغْفِرْ لِي، رَبِّ اغْفِرْ لِي',
    transliteration: "Rabbighfir li, Rabbighfir li",
    translation: 'My Lord, forgive me. My Lord, forgive me.',
    translationBn: 'হে আমার রব! আমাকে ক্ষমা কর। হে আমার রব! আমাকে ক্ষমা কর।',
    reference: 'Ibn Majah',
    icon: BookOpen,
  },
  {
    id: 38,
    category: 'prayer',
    categoryBn: 'নামাজ',
    title: 'Tashahhud',
    titleBn: 'তাশাহহুদ',
    arabic: 'التَّحِيَّاتُ لِلَّهِ وَالصَّلَوَاتُ وَالطَّيِّبَاتُ، السَّلَامُ عَلَيْكَ أَيُّهَا النَّبِيُّ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ',
    transliteration: "At-tahiyyatu lillahi was-salawatu wat-tayyibat, as-salamu alayka ayyuhan-Nabiyyu wa rahmatullahi wa barakatuh",
    translation: 'All compliments, prayers and pure words are due to Allah. Peace be upon you, O Prophet, and the mercy of Allah and His blessings.',
    translationBn: 'সকল সম্মান, নামাজ ও পবিত্র কথা আল্লাহর জন্য। হে নবী! আপনার উপর শান্তি, আল্লাহর রহমত ও বরকত বর্ষিত হোক।',
    reference: 'Sahih Bukhari',
    icon: BookOpen,
  },
  {
    id: 39,
    category: 'prayer',
    categoryBn: 'নামাজ',
    title: 'After Prayer',
    titleBn: 'নামাজের পর',
    arabic: 'أَسْتَغْفِرُ اللَّهَ، أَسْتَغْفِرُ اللَّهَ، أَسْتَغْفِرُ اللَّهَ',
    transliteration: "Astaghfirullah, Astaghfirullah, Astaghfirullah",
    translation: 'I seek forgiveness from Allah. I seek forgiveness from Allah. I seek forgiveness from Allah.',
    translationBn: 'আমি আল্লাহর কাছে ক্ষমা চাই। আমি আল্লাহর কাছে ক্ষমা চাই। আমি আল্লাহর কাছে ক্ষমা চাই।',
    reference: 'Muslim',
    icon: BookOpen,
  },
  {
    id: 40,
    category: 'prayer',
    categoryBn: 'নামাজ',
    title: 'Ayatul Kursi After Prayer',
    titleBn: 'নামাজের পর আয়াতুল কুরসি',
    arabic: 'اللَّهُ لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ',
    transliteration: "Allahu la ilaha illa Huwal-Hayyul-Qayyum, la ta'khudhuhu sinatun wa la nawm",
    translation: 'Allah! There is no god but He, the Living, the Self-subsisting. Neither slumber nor sleep overtakes Him.',
    translationBn: 'আল্লাহ! তিনি ছাড়া কোনো উপাস্য নেই, তিনি চিরঞ্জীব, সর্বসত্তার ধারক। তন্দ্রা বা নিদ্রা তাঁকে স্পর্শ করে না।',
    reference: 'Quran 2:255',
    icon: BookOpen,
  },

  // === HOME DUAS (41-48) ===
  {
    id: 41,
    category: 'home',
    categoryBn: 'ঘর',
    title: 'When Entering Home',
    titleBn: 'ঘরে প্রবেশের সময়',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَ الْمَوْلِجِ وَخَيْرَ الْمَخْرَجِ، بِسْمِ اللَّهِ وَلَجْنَا، وَبِسْمِ اللَّهِ خَرَجْنَا',
    transliteration: "Allahumma inni as'aluka khayral-mawlij wa khayral-makhraj. Bismillahi walajna, wa bismillahi kharajna",
    translation: 'O Allah, I ask You for the good of entering and the good of leaving. In the name of Allah we enter and in the name of Allah we leave.',
    translationBn: 'হে আল্লাহ! আমি প্রবেশের কল্যাণ ও বাহির হওয়ার কল্যাণ চাই। আল্লাহর নামে আমরা প্রবেশ করলাম এবং আল্লাহর নামে বাহির হলাম।',
    reference: 'Abu Dawud',
    icon: DoorOpen,
  },
  {
    id: 42,
    category: 'home',
    categoryBn: 'ঘর',
    title: 'When Leaving Home',
    titleBn: 'ঘর থেকে বের হওয়ার সময়',
    arabic: 'بِسْمِ اللَّهِ، تَوَكَّلْتُ عَلَى اللَّهِ، وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ',
    transliteration: "Bismillah, tawakkaltu alallah, wa la hawla wa la quwwata illa billah",
    translation: 'In the name of Allah, I place my trust in Allah, and there is no might nor power except with Allah.',
    translationBn: 'আল্লাহর নামে, আমি আল্লাহর উপর ভরসা করলাম এবং আল্লাহ ছাড়া কোনো শক্তি বা ক্ষমতা নেই।',
    reference: 'Abu Dawud',
    icon: DoorOpen,
  },
  {
    id: 43,
    category: 'home',
    categoryBn: 'ঘর',
    title: 'New Home Blessing',
    titleBn: 'নতুন ঘরের বরকত',
    arabic: 'اللَّهُمَّ بَارِكْ لَنَا فِي بَيْتِنَا وَفِي رِزْقِنَا وَفِي أَهْلِنَا',
    transliteration: "Allahumma barik lana fi baytina wa fi rizqina wa fi ahlina",
    translation: 'O Allah, bless us in our home, in our provision, and in our family.',
    translationBn: 'হে আল্লাহ! আমাদের ঘরে, রিযিকে এবং পরিবারে বরকত দাও।',
    reference: 'Tabarani',
    icon: Home,
  },
  {
    id: 44,
    category: 'home',
    categoryBn: 'ঘর',
    title: 'When Wearing Clothes',
    titleBn: 'কাপড় পরার সময়',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي كَسَانِي هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ',
    transliteration: "Alhamdu lillahil-ladhi kasani hadha wa razaqaneehi min ghayri hawlin minni wa la quwwah",
    translation: 'All praise is for Allah who clothed me with this and provided it for me without any might or power from myself.',
    translationBn: 'সকল প্রশংসা আল্লাহর যিনি আমাকে এই কাপড় পরিয়েছেন এবং আমার কোনো শক্তি বা সামর্থ্য ছাড়াই দান করেছেন।',
    reference: 'Abu Dawud',
    icon: Shirt,
  },
  {
    id: 45,
    category: 'home',
    categoryBn: 'ঘর',
    title: 'When Looking in Mirror',
    titleBn: 'আয়নায় দেখার সময়',
    arabic: 'اللَّهُمَّ أَنْتَ حَسَّنْتَ خَلْقِي فَحَسِّنْ خُلُقِي',
    transliteration: "Allahumma anta hassanta khalqi fa hassin khuluqi",
    translation: 'O Allah, just as You have made my external features beautiful, make my character beautiful as well.',
    translationBn: 'হে আল্লাহ! তুমি যেমন আমার আকৃতি সুন্দর করেছ, তেমনি আমার চরিত্রও সুন্দর কর।',
    reference: 'Ahmad',
    icon: Eye,
  },
  {
    id: 46,
    category: 'home',
    categoryBn: 'ঘর',
    title: 'When Entering Bathroom',
    titleBn: 'বাথরুমে প্রবেশকালে',
    arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ',
    transliteration: "Allahumma inni a'udhu bika minal-khubuthi wal-khaba'ith",
    translation: 'O Allah, I seek refuge in You from the male and female devils.',
    translationBn: 'হে আল্লাহ! আমি পুরুষ ও নারী শয়তান থেকে তোমার কাছে আশ্রয় চাই।',
    reference: 'Sahih Bukhari',
    icon: Droplets,
  },
  {
    id: 47,
    category: 'home',
    categoryBn: 'ঘর',
    title: 'When Exiting Bathroom',
    titleBn: 'বাথরুম থেকে বের হওয়ার সময়',
    arabic: 'غُفْرَانَكَ',
    transliteration: "Ghufranaka",
    translation: 'I seek Your forgiveness.',
    translationBn: 'আমি তোমার ক্ষমা চাই।',
    reference: 'Abu Dawud',
    icon: Droplets,
  },

  // === PROTECTION DUAS (48-56) ===
  {
    id: 48,
    category: 'protection',
    categoryBn: 'সুরক্ষা',
    title: 'Seeking Refuge from Evil',
    titleBn: 'মন্দ থেকে আশ্রয়',
    arabic: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ',
    transliteration: "A'udhu bikalimaat-illahit-tammaati min sharri ma khalaq",
    translation: 'I seek refuge in the perfect words of Allah from the evil of what He has created.',
    translationBn: 'আমি আল্লাহর পরিপূর্ণ কালামের মাধ্যমে তাঁর সৃষ্টির সকল অনিষ্ট থেকে আশ্রয় চাই।',
    reference: 'Muslim',
    icon: Shield,
  },
  {
    id: 49,
    category: 'protection',
    categoryBn: 'সুরক্ষা',
    title: 'Protection from Evil Eye',
    titleBn: 'বদ নজর থেকে সুরক্ষা',
    arabic: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّةِ مِنْ كُلِّ شَيْطَانٍ وَهَامَّةٍ، وَمِنْ كُلِّ عَيْنٍ لَامَّةٍ',
    transliteration: "A'udhu bi kalimatillahit-tammah min kulli shaytanin wa hammah, wa min kulli aynin lammah",
    translation: 'I seek refuge in the perfect words of Allah from every devil and poisonous pest, and from every evil eye.',
    translationBn: 'আমি আল্লাহর পরিপূর্ণ কালামের মাধ্যমে প্রতিটি শয়তান ও বিষাক্ত কীট থেকে এবং প্রতিটি কুদৃষ্টি থেকে আশ্রয় চাই।',
    reference: 'Sahih Bukhari',
    icon: Eye,
  },
  {
    id: 50,
    category: 'protection',
    categoryBn: 'সুরক্ষা',
    title: 'Protection from Harm',
    titleBn: 'ক্ষতি থেকে সুরক্ষা',
    arabic: 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ',
    transliteration: "Bismillahil-ladhi la yadurru ma'asmihi shay'un fil-ardi wa la fis-sama'i wa huwas-samee'ul-aleem",
    translation: 'In the name of Allah with Whose name nothing is harmed on earth nor in the heavens and He is the All-Hearing, the All-Knowing.',
    translationBn: 'আল্লাহর নামে, যার নাম নিলে আকাশ ও পৃথিবীর কোনো কিছু ক্ষতি করতে পারে না এবং তিনি সর্বশ্রোতা, সর্বজ্ঞ।',
    reference: 'Abu Dawud',
    icon: Shield,
  },
  {
    id: 51,
    category: 'protection',
    categoryBn: 'সুরক্ষা',
    title: 'During Thunderstorm',
    titleBn: 'বজ্রপাতের সময়',
    arabic: 'سُبْحَانَ الَّذِي يُسَبِّحُ الرَّعْدُ بِحَمْدِهِ وَالْمَلَائِكَةُ مِنْ خِيفَتِهِ',
    transliteration: "Subhanal-ladhi yusabbihur-ra'du bihamdihi wal-mala'ikatu min khifatih",
    translation: 'Glory be to Him Whom thunder and angels glorify due to fear of Him.',
    translationBn: 'পবিত্র সেই সত্তা যার প্রশংসায় বজ্র এবং ভয়ে ফেরেশতারা তাসবীহ পাঠ করে।',
    reference: 'Malik',
    icon: Cloud,
  },
  {
    id: 52,
    category: 'protection',
    categoryBn: 'সুরক্ষা',
    title: 'When It Rains',
    titleBn: 'বৃষ্টির সময়',
    arabic: 'اللَّهُمَّ صَيِّبًا نَافِعًا',
    transliteration: "Allahumma sayyiban nafi'a",
    translation: 'O Allah, make it a beneficial rain.',
    translationBn: 'হে আল্লাহ! এটাকে উপকারী বৃষ্টি কর।',
    reference: 'Sahih Bukhari',
    icon: Umbrella,
  },
  {
    id: 53,
    category: 'protection',
    categoryBn: 'সুরক্ষা',
    title: 'For Safety',
    titleBn: 'নিরাপত্তার জন্য',
    arabic: 'اللَّهُمَّ احْفَظْنِي مِنْ بَيْنِ يَدَيَّ، وَمِنْ خَلْفِي، وَعَنْ يَمِينِي، وَعَنْ شِمَالِي، وَمِنْ فَوْقِي',
    transliteration: "Allahumma ihfadhni min bayni yadayya, wa min khalfi, wa an yameeni, wa an shimali, wa min fawqi",
    translation: 'O Allah, protect me from my front and from behind me, from my right and from my left, and from above me.',
    translationBn: 'হে আল্লাহ! আমাকে আমার সামনে থেকে, পেছন থেকে, ডান থেকে, বাম থেকে এবং উপর থেকে রক্ষা কর।',
    reference: 'Abu Dawud',
    icon: Shield,
  },

  // === HEALTH DUAS (54-61) ===
  {
    id: 54,
    category: 'health',
    categoryBn: 'স্বাস্থ্য',
    title: 'For Healing',
    titleBn: 'আরোগ্যের জন্য',
    arabic: 'اللَّهُمَّ رَبَّ النَّاسِ أَذْهِبِ الْبَأْسَ، اشْفِهِ وَأَنْتَ الشَّافِي، لَا شِفَاءَ إِلَّا شِفَاؤُكَ، شِفَاءً لَا يُغَادِرُ سَقَمًا',
    transliteration: "Allahumma Rabban-nas, adhhibil-ba's, ishfihi wa antash-Shafi, la shifa'a illa shifa'uk, shifa'an la yughadiru saqama",
    translation: 'O Allah, Lord of mankind, remove the affliction. Heal, for You are the Healer. There is no healing except Your healing, a healing that leaves no illness behind.',
    translationBn: 'হে আল্লাহ! মানুষের প্রতিপালক, কষ্ট দূর কর, আরোগ্য দান কর কেননা তুমিই আরোগ্যদাতা। তোমার আরোগ্য ছাড়া কোনো আরোগ্য নেই, এমন আরোগ্য যা কোনো রোগ রেখে যায় না।',
    reference: 'Sahih Bukhari',
    icon: Stethoscope,
  },
  {
    id: 55,
    category: 'health',
    categoryBn: 'স্বাস্থ্য',
    title: 'When Visiting the Sick',
    titleBn: 'অসুস্থ ব্যক্তিকে দেখতে গেলে',
    arabic: 'لَا بَأْسَ، طَهُورٌ إِنْ شَاءَ اللَّهُ',
    transliteration: "La ba'sa, tahoorun insha'Allah",
    translation: 'No harm, it is purification, if Allah wills.',
    translationBn: 'কোনো সমস্যা নেই, আল্লাহ চাইলে এটা পবিত্রতা স্বরূপ।',
    reference: 'Sahih Bukhari',
    icon: Stethoscope,
  },
  {
    id: 56,
    category: 'health',
    categoryBn: 'স্বাস্থ্য',
    title: 'When in Pain',
    titleBn: 'ব্যথা অনুভব করলে',
    arabic: 'بِسْمِ اللَّهِ، أَعُوذُ بِعِزَّةِ اللَّهِ وَقُدْرَتِهِ مِنْ شَرِّ مَا أَجِدُ وَأُحَاذِرُ',
    transliteration: "Bismillah, a'udhu bi izzatillahi wa qudratihi min sharri ma ajidu wa uhadhir",
    translation: 'In the name of Allah, I seek refuge in Allah\'s might and power from the evil of what I feel and fear.',
    translationBn: 'আল্লাহর নামে, আমি যা অনুভব করছি এবং যার ভয় করছি তার অনিষ্ট থেকে আল্লাহর মর্যাদা ও ক্ষমতার মাধ্যমে আশ্রয় চাই।',
    reference: 'Muslim',
    icon: Stethoscope,
  },
  {
    id: 57,
    category: 'health',
    categoryBn: 'স্বাস্থ্য',
    title: 'After Sneezing',
    titleBn: 'হাঁচির পর',
    arabic: 'الْحَمْدُ لِلَّهِ',
    transliteration: "Alhamdulillah",
    translation: 'All praise is for Allah.',
    translationBn: 'সকল প্রশংসা আল্লাহর জন্য।',
    reference: 'Sahih Bukhari',
    icon: Stethoscope,
  },
  {
    id: 58,
    category: 'health',
    categoryBn: 'স্বাস্থ্য',
    title: 'Reply to Sneezer',
    titleBn: 'হাঁচিদাতাকে জবাব',
    arabic: 'يَرْحَمُكَ اللَّهُ',
    transliteration: "Yarhamukallah",
    translation: 'May Allah have mercy on you.',
    translationBn: 'আল্লাহ তোমার উপর রহম করুন।',
    reference: 'Sahih Bukhari',
    icon: Stethoscope,
  },

  // === FAMILY DUAS (59-67) ===
  {
    id: 59,
    category: 'family',
    categoryBn: 'পরিবার',
    title: 'For Parents',
    titleBn: 'পিতামাতার জন্য',
    arabic: 'رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا',
    transliteration: "Rabbir-hamhuma kama rabbayanee sagheera",
    translation: 'My Lord, have mercy upon them as they brought me up when I was small.',
    translationBn: 'হে আমার রব! তাদের প্রতি দয়া কর যেমন তারা আমাকে ছোটকালে লালন-পালন করেছেন।',
    reference: 'Quran 17:24',
    icon: Users,
  },
  {
    id: 60,
    category: 'family',
    categoryBn: 'পরিবার',
    title: 'For Righteous Children',
    titleBn: 'নেককার সন্তানের জন্য',
    arabic: 'رَبِّ هَبْ لِي مِنَ الصَّالِحِينَ',
    transliteration: "Rabbi hab li minas-saliheen",
    translation: 'My Lord, grant me from among the righteous.',
    translationBn: 'হে আমার রব! আমাকে নেক সন্তান দান কর।',
    reference: 'Quran 37:100',
    icon: Baby,
  },
  {
    id: 61,
    category: 'family',
    categoryBn: 'পরিবার',
    title: 'For Spouse and Children',
    titleBn: 'স্ত্রী ও সন্তানের জন্য',
    arabic: 'رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ وَاجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا',
    transliteration: "Rabbana hab lana min azwajina wa dhurriyyatina qurrata a'yunin waj'alna lil-muttaqina imama",
    translation: 'Our Lord, grant us from among our wives and offspring comfort to our eyes and make us an example for the righteous.',
    translationBn: 'হে আমাদের রব! আমাদের স্ত্রী ও সন্তানদের পক্ষ থেকে আমাদের চোখের শীতলতা দাও এবং আমাদের মুত্তাকীদের নেতা বানাও।',
    reference: 'Quran 25:74',
    icon: Users,
  },
  {
    id: 62,
    category: 'family',
    categoryBn: 'পরিবার',
    title: 'For Family Harmony',
    titleBn: 'পারিবারিক সম্প্রীতির জন্য',
    arabic: 'اللَّهُمَّ أَصْلِحْ بَيْنَنَا، وَأَلِّفْ بَيْنَ قُلُوبِنَا',
    transliteration: "Allahumma aslih baynana, wa allif bayna quloobina",
    translation: 'O Allah, reconcile between us and bring our hearts together.',
    translationBn: 'হে আল্লাহ! আমাদের মধ্যে মিলমিশ করে দাও এবং আমাদের হৃদয়গুলোকে জুড়ে দাও।',
    reference: 'Muslim',
    icon: Heart,
  },
  {
    id: 63,
    category: 'family',
    categoryBn: 'পরিবার',
    title: 'Newlyweds Prayer',
    titleBn: 'নবদম্পতির দোয়া',
    arabic: 'بَارَكَ اللَّهُ لَكَ وَبَارَكَ عَلَيْكَ وَجَمَعَ بَيْنَكُمَا فِي خَيْرٍ',
    transliteration: "Barakallahu laka, wa baraka alayka, wa jama'a baynakuma fi khayr",
    translation: 'May Allah bless you, and shower His blessings upon you, and join you together in goodness.',
    translationBn: 'আল্লাহ তোমার জন্য বরকত দিন, তোমার উপর বরকত বর্ষণ করুন এবং তোমাদের দুজনকে কল্যাণে একত্রিত করুন।',
    reference: 'Abu Dawud',
    icon: Heart,
  },

  // === FORGIVENESS DUAS (64-72) ===
  {
    id: 64,
    category: 'forgiveness',
    categoryBn: 'ক্ষমা',
    title: 'Seeking Forgiveness',
    titleBn: 'ক্ষমা প্রার্থনা',
    arabic: 'أَسْتَغْفِرُ اللَّهَ الْعَظِيمَ الَّذِي لَا إِلَهَ إِلَّا هُوَ الْحَيَّ الْقَيُّومَ وَأَتُوبُ إِلَيْهِ',
    transliteration: "Astaghfirullaha-l-adheemal-ladhi la ilaha illa Huwal-Hayyul-Qayyum wa atubu ilayh",
    translation: 'I seek forgiveness from Allah the Almighty, besides Whom there is no god, the Ever Living, the Self-Subsisting, and I repent to Him.',
    translationBn: 'আমি মহান আল্লাহর কাছে ক্ষমা চাই যিনি ছাড়া কোনো উপাস্য নেই, চিরঞ্জীব, সর্বসত্তার ধারক এবং তাঁর কাছে তওবা করি।',
    reference: 'Abu Dawud',
    icon: Sparkles,
  },
  {
    id: 65,
    category: 'forgiveness',
    categoryBn: 'ক্ষমা',
    title: 'Complete Repentance',
    titleBn: 'পূর্ণ তওবা',
    arabic: 'رَبِّ اغْفِرْ لِي وَتُبْ عَلَيَّ إِنَّكَ أَنْتَ التَّوَّابُ الرَّحِيمُ',
    transliteration: "Rabbighfir li wa tub alayya innaka antat-Tawwabur-Raheem",
    translation: 'My Lord, forgive me and accept my repentance. Indeed, You are the Accepting of repentance, the Merciful.',
    translationBn: 'হে আমার রব! আমাকে ক্ষমা কর এবং আমার তওবা কবুল কর। নিশ্চয়ই তুমি তওবা কবুলকারী, দয়ালু।',
    reference: 'Tirmidhi',
    icon: Sparkles,
  },
  {
    id: 66,
    category: 'forgiveness',
    categoryBn: 'ক্ষমা',
    title: 'For All Sins',
    titleBn: 'সকল গুনাহের জন্য',
    arabic: 'اللَّهُمَّ اغْفِرْ لِي ذَنْبِي كُلَّهُ، دِقَّهُ وَجِلَّهُ، وَأَوَّلَهُ وَآخِرَهُ، وَعَلَانِيَتَهُ وَسِرَّهُ',
    transliteration: "Allahummaghfir li dhanbi kullahu, diqqahu wa jillahu, wa awwalahu wa akhirahu, wa alaniyyatahu wa sirrahu",
    translation: 'O Allah, forgive all my sins, the small and the great, the first and the last, the open and the secret.',
    translationBn: 'হে আল্লাহ! আমার সব গুনাহ মাফ কর, ছোট-বড়, প্রথম-শেষ, প্রকাশ্য ও গোপন।',
    reference: 'Muslim',
    icon: Sparkles,
  },
  {
    id: 67,
    category: 'forgiveness',
    categoryBn: 'ক্ষমা',
    title: 'Prophet\'s Forgiveness Prayer',
    titleBn: 'নবীর ক্ষমার দোয়া',
    arabic: 'رَبِّ اغْفِرْ وَارْحَمْ وَأَنْتَ خَيْرُ الرَّاحِمِينَ',
    transliteration: "Rabbighfir warham wa anta khayrur-rahimeen",
    translation: 'My Lord, forgive and have mercy, and You are the best of the merciful.',
    translationBn: 'হে আমার রব! ক্ষমা কর ও দয়া কর, তুমিই শ্রেষ্ঠ দয়ালু।',
    reference: 'Quran 23:118',
    icon: Sparkles,
  },

  // === GENERAL DUAS (68-100) ===
  {
    id: 68,
    category: 'general',
    categoryBn: 'সাধারণ',
    title: 'For Good in Both Worlds',
    titleBn: 'উভয় জগতের কল্যাণ',
    arabic: 'رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ',
    transliteration: "Rabbana atina fid-dunya hasanatan wa fil-akhirati hasanatan wa qina adhaban-nar",
    translation: 'Our Lord, give us good in this world and good in the Hereafter, and protect us from the punishment of the Fire.',
    translationBn: 'হে আমাদের প্রতিপালক! আমাদের দুনিয়াতে কল্যাণ দাও এবং আখিরাতেও কল্যাণ দাও এবং আমাদের জাহান্নামের আগুন থেকে রক্ষা কর।',
    reference: 'Quran 2:201',
    icon: Heart,
  },
  {
    id: 69,
    category: 'general',
    categoryBn: 'সাধারণ',
    title: 'For Guidance',
    titleBn: 'হেদায়াতের জন্য',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ الْهُدَى وَالتُّقَى وَالْعَفَافَ وَالْغِنَى',
    transliteration: "Allahumma inni as'alukal-huda wat-tuqa wal-afafa wal-ghina",
    translation: 'O Allah, I ask You for guidance, piety, chastity, and self-sufficiency.',
    translationBn: 'হে আল্লাহ! আমি তোমার কাছে হেদায়াত, তাকওয়া, পবিত্রতা ও অমুখাপেক্ষিতা চাই।',
    reference: 'Muslim',
    icon: Heart,
  },
  {
    id: 70,
    category: 'general',
    categoryBn: 'সাধারণ',
    title: 'For Beneficial Knowledge',
    titleBn: 'উপকারী জ্ঞানের জন্য',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا، وَرِزْقًا طَيِّبًا، وَعَمَلًا مُتَقَبَّلًا',
    transliteration: "Allahumma inni as'aluka ilman nafi'an, wa rizqan tayyiban, wa amalan mutaqabbala",
    translation: 'O Allah, I ask You for beneficial knowledge, goodly provision, and acceptable deeds.',
    translationBn: 'হে আল্লাহ! আমি তোমার কাছে উপকারী জ্ঞান, হালাল রিযিক এবং কবুলযোগ্য আমল চাই।',
    reference: 'Ibn Majah',
    icon: BookOpen,
  },
  {
    id: 71,
    category: 'general',
    categoryBn: 'সাধারণ',
    title: 'For Patience',
    titleBn: 'ধৈর্যের জন্য',
    arabic: 'رَبَّنَا أَفْرِغْ عَلَيْنَا صَبْرًا وَثَبِّتْ أَقْدَامَنَا',
    transliteration: "Rabbana afrigh alayna sabran wa thabbit aqdamana",
    translation: 'Our Lord, pour upon us patience and plant firmly our feet.',
    translationBn: 'হে আমাদের রব! আমাদের উপর ধৈর্য ঢেলে দাও এবং আমাদের পা দৃঢ় রাখ।',
    reference: 'Quran 2:250',
    icon: Heart,
  },
  {
    id: 72,
    category: 'general',
    categoryBn: 'সাধারণ',
    title: 'For a Good Death',
    titleBn: 'উত্তম মৃত্যুর জন্য',
    arabic: 'اللَّهُمَّ اجْعَلْ خَيْرَ أَعْمَالِي خَوَاتِمَهَا، وَخَيْرَ أَيَّامِي يَوْمَ أَلْقَاكَ',
    transliteration: "Allahumma ij'al khayra a'mali khawatimaha, wa khayra ayyami yawma alqak",
    translation: 'O Allah, make the best of my deeds my last ones, and the best of my days the day I meet You.',
    translationBn: 'হে আল্লাহ! আমার সর্বোত্তম আমল শেষের আমল বানাও এবং আমার সর্বোত্তম দিন তোমার সাথে সাক্ষাতের দিন বানাও।',
    reference: 'Tabarani',
    icon: Heart,
  },
  {
    id: 73,
    category: 'general',
    categoryBn: 'সাধারণ',
    title: 'For Steadfastness',
    titleBn: 'অবিচলতার জন্য',
    arabic: 'يَا مُقَلِّبَ الْقُلُوبِ ثَبِّتْ قَلْبِي عَلَى دِينِكَ',
    transliteration: "Ya muqallibal-qulubi thabbit qalbi ala deenik",
    translation: 'O Turner of the hearts, make my heart firm upon Your religion.',
    translationBn: 'হে হৃদয় পরিবর্তনকারী! আমার হৃদয়কে তোমার দ্বীনের উপর অবিচল রাখ।',
    reference: 'Tirmidhi',
    icon: Heart,
  },
  {
    id: 74,
    category: 'general',
    categoryBn: 'সাধারণ',
    title: 'For Gratitude',
    titleBn: 'কৃতজ্ঞতার জন্য',
    arabic: 'اللَّهُمَّ أَعِنِّي عَلَى ذِكْرِكَ وَشُكْرِكَ وَحُسْنِ عِبَادَتِكَ',
    transliteration: "Allahumma a'inni ala dhikrika wa shukrika wa husni ibadatik",
    translation: 'O Allah, help me to remember You, thank You, and worship You in the best way.',
    translationBn: 'হে আল্লাহ! তোমার যিকির, শোকর এবং উত্তম ইবাদতে আমাকে সাহায্য কর।',
    reference: 'Abu Dawud',
    icon: Heart,
  },
  {
    id: 75,
    category: 'general',
    categoryBn: 'সাধারণ',
    title: 'For Contentment',
    titleBn: 'সন্তুষ্টির জন্য',
    arabic: 'اللَّهُمَّ قَنِّعْنِي بِمَا رَزَقْتَنِي، وَبَارِكْ لِي فِيهِ',
    transliteration: "Allahumma qanni'ni bima razaqtani, wa barik li fih",
    translation: 'O Allah, make me content with what You have provided me and put blessings in it for me.',
    translationBn: 'হে আল্লাহ! তুমি আমাকে যা দিয়েছ তাতে সন্তুষ্ট রাখ এবং তাতে বরকত দাও।',
    reference: 'Hakim',
    icon: Heart,
  },
  {
    id: 76,
    category: 'general',
    categoryBn: 'সাধারণ',
    title: 'For Strength',
    titleBn: 'শক্তির জন্য',
    arabic: 'لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ الْعَلِيِّ الْعَظِيمِ',
    transliteration: "La hawla wa la quwwata illa billahil-aliyyil-adheem",
    translation: 'There is no might nor power except with Allah, the Most High, the Most Great.',
    translationBn: 'আল্লাহ ছাড়া কোনো শক্তি বা ক্ষমতা নেই, যিনি সুউচ্চ ও মহান।',
    reference: 'Sahih Bukhari',
    icon: Heart,
  },
  {
    id: 77,
    category: 'general',
    categoryBn: 'সাধারণ',
    title: 'For Success',
    titleBn: 'সাফল্যের জন্য',
    arabic: 'رَبِّ اشْرَحْ لِي صَدْرِي، وَيَسِّرْ لِي أَمْرِي',
    transliteration: "Rabbish rahli sadri, wa yassir li amri",
    translation: 'My Lord, expand for me my chest and ease for me my task.',
    translationBn: 'হে আমার রব! আমার বুক প্রশস্ত করে দাও এবং আমার কাজ সহজ করে দাও।',
    reference: 'Quran 20:25-26',
    icon: Sparkles,
  },
  {
    id: 78,
    category: 'general',
    categoryBn: 'সাধারণ',
    title: 'For Steadfast Heart',
    titleBn: 'দৃঢ় হৃদয়ের জন্য',
    arabic: 'رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِنْ لَدُنْكَ رَحْمَةً',
    transliteration: "Rabbana la tuzigh quloobana ba'da idh hadaytana wa hab lana min ladunka rahmah",
    translation: 'Our Lord, let not our hearts deviate after You have guided us and grant us from Yourself mercy.',
    translationBn: 'হে আমাদের রব! হেদায়াত দেওয়ার পর আমাদের হৃদয় বক্র করো না এবং তোমার কাছ থেকে আমাদের রহমত দাও।',
    reference: 'Quran 3:8',
    icon: Heart,
  },
  {
    id: 79,
    category: 'general',
    categoryBn: 'সাধারণ',
    title: 'For Light',
    titleBn: 'আলোর জন্য',
    arabic: 'اللَّهُمَّ اجْعَلْ فِي قَلْبِي نُورًا، وَفِي لِسَانِي نُورًا، وَفِي بَصَرِي نُورًا',
    transliteration: "Allahummaj'al fi qalbi nuran, wa fi lisani nuran, wa fi basari nuran",
    translation: 'O Allah, place light in my heart, and on my tongue light, and in my eyes light.',
    translationBn: 'হে আল্লাহ! আমার হৃদয়ে, জিহবায় এবং চোখে আলো দাও।',
    reference: 'Muslim',
    icon: Sparkles,
  },
  {
    id: 80,
    category: 'general',
    categoryBn: 'সাধারণ',
    title: 'For Protection from Laziness',
    titleBn: 'অলসতা থেকে রক্ষা',
    arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْعَجْزِ وَالْكَسَلِ، وَالْجُبْنِ وَالْهَرَمِ وَالْبُخْلِ',
    transliteration: "Allahumma inni a'udhu bika minal-ajzi wal-kasal, wal-jubni wal-harami wal-bukhl",
    translation: 'O Allah, I seek refuge in You from incapacity, laziness, cowardice, old age, and miserliness.',
    translationBn: 'হে আল্লাহ! অক্ষমতা, অলসতা, কাপুরুষতা, বার্ধক্য ও কৃপণতা থেকে তোমার কাছে আশ্রয় চাই।',
    reference: 'Sahih Bukhari',
    icon: Shield,
  },
  {
    id: 81,
    category: 'general',
    categoryBn: 'সাধারণ',
    title: 'For Provision',
    titleBn: 'রিযিকের জন্য',
    arabic: 'اللَّهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ، وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ',
    transliteration: "Allahummakfini bihalalika an haramik, wa aghnini bifadlika amman siwak",
    translation: 'O Allah, suffice me with what You have allowed instead of what You have forbidden, and make me independent of all others besides You.',
    translationBn: 'হে আল্লাহ! হারামের বদলে হালাল দিয়ে আমার জন্য যথেষ্ট কর এবং তোমার অনুগ্রহে আমাকে অন্যদের থেকে অমুখাপেক্ষী কর।',
    reference: 'Tirmidhi',
    icon: Heart,
  },
  {
    id: 82,
    category: 'general',
    categoryBn: 'সাধারণ',
    title: 'For Peace',
    titleBn: 'শান্তির জন্য',
    arabic: 'اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ، تَبَارَكْتَ يَا ذَا الْجَلَالِ وَالْإِكْرَامِ',
    transliteration: "Allahumma antas-salam wa minkas-salam, tabarakta ya dhal-jalali wal-ikram",
    translation: 'O Allah, You are Peace and from You comes peace. Blessed are You, O Owner of majesty and honor.',
    translationBn: 'হে আল্লাহ! তুমি শান্তি এবং তোমার কাছ থেকেই শান্তি আসে। তুমি বরকতময়, হে মহিমা ও সম্মানের অধিকারী।',
    reference: 'Muslim',
    icon: Heart,
  },
  {
    id: 83,
    category: 'general',
    categoryBn: 'সাধারণ',
    title: 'For Mercy',
    titleBn: 'রহমতের জন্য',
    arabic: 'رَبِّ إِنِّي لِمَا أَنْزَلْتَ إِلَيَّ مِنْ خَيْرٍ فَقِيرٌ',
    transliteration: "Rabbi inni lima anzalta ilayya min khayrin faqeer",
    translation: 'My Lord, indeed I am, for whatever good You would send down to me, in need.',
    translationBn: 'হে আমার রব! তুমি যে কল্যাণ আমার কাছে পাঠাবে তার জন্য আমি মুখাপেক্ষী।',
    reference: 'Quran 28:24',
    icon: Heart,
  },
  {
    id: 84,
    category: 'general',
    categoryBn: 'সাধারণ',
    title: 'For Relief from Anxiety',
    titleBn: 'দুশ্চিন্তা থেকে মুক্তি',
    arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ، وَالْعَجْزِ وَالْكَسَلِ',
    transliteration: "Allahumma inni a'udhu bika minal-hammi wal-hazan, wal-ajzi wal-kasal",
    translation: 'O Allah, I seek refuge in You from anxiety and sorrow, weakness and laziness.',
    translationBn: 'হে আল্লাহ! দুশ্চিন্তা ও দুঃখ, দুর্বলতা ও অলসতা থেকে তোমার কাছে আশ্রয় চাই।',
    reference: 'Sahih Bukhari',
    icon: Shield,
  },
  {
    id: 85,
    category: 'general',
    categoryBn: 'সাধারণ',
    title: 'For Entering Paradise',
    titleBn: 'জান্নাতে প্রবেশের জন্য',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ الْجَنَّةَ وَأَعُوذُ بِكَ مِنَ النَّارِ',
    transliteration: "Allahumma inni as'alukal-jannah wa a'udhu bika minan-nar",
    translation: 'O Allah, I ask You for Paradise and seek refuge in You from the Fire.',
    translationBn: 'হে আল্লাহ! আমি তোমার কাছে জান্নাত চাই এবং জাহান্নাম থেকে আশ্রয় চাই।',
    reference: 'Abu Dawud',
    icon: Sparkles,
  },
  {
    id: 86,
    category: 'general',
    categoryBn: 'সাধারণ',
    title: 'For Truthfulness',
    titleBn: 'সত্যবাদিতার জন্য',
    arabic: 'اللَّهُمَّ اهْدِنِي لِأَحْسَنِ الْأَخْلَاقِ، لَا يَهْدِي لِأَحْسَنِهَا إِلَّا أَنْتَ',
    transliteration: "Allahummahdini li-ahsanil-akhlaq, la yahdi li-ahsaniha illa ant",
    translation: 'O Allah, guide me to the best of character. None can guide to the best of it but You.',
    translationBn: 'হে আল্লাহ! আমাকে উত্তম চরিত্রের দিকে পরিচালিত কর। তুমি ছাড়া কেউ উত্তম চরিত্রের দিকে পরিচালিত করতে পারে না।',
    reference: 'Muslim',
    icon: Heart,
  },
  {
    id: 87,
    category: 'general',
    categoryBn: 'সাধারণ',
    title: 'For Humility',
    titleBn: 'বিনয়ের জন্য',
    arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ عِلْمٍ لَا يَنْفَعُ، وَمِنْ قَلْبٍ لَا يَخْشَعُ',
    transliteration: "Allahumma inni a'udhu bika min ilmin la yanfa', wa min qalbin la yakhsha'",
    translation: 'O Allah, I seek refuge in You from knowledge that is not beneficial and from a heart that does not fear.',
    translationBn: 'হে আল্লাহ! অনুপকারী জ্ঞান এবং ভয়হীন অন্তর থেকে তোমার কাছে আশ্রয় চাই।',
    reference: 'Muslim',
    icon: Heart,
  },
  {
    id: 88,
    category: 'general',
    categoryBn: 'সাধারণ',
    title: 'For Faith',
    titleBn: 'ঈমানের জন্য',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ إِيمَانًا لَا يَرْتَدُّ، وَنَعِيمًا لَا يَنْفَدُ',
    transliteration: "Allahumma inni as'aluka imanan la yartadd, wa na'iman la yanfad",
    translation: 'O Allah, I ask You for faith that does not retreat and blessings that do not diminish.',
    translationBn: 'হে আল্লাহ! আমি তোমার কাছে এমন ঈমান চাই যা পিছু হটে না এবং এমন নেয়ামত যা শেষ হয় না।',
    reference: 'Ahmad',
    icon: Sparkles,
  },
  {
    id: 89,
    category: 'general',
    categoryBn: 'সাধারণ',
    title: 'For Understanding',
    titleBn: 'বুঝের জন্য',
    arabic: 'رَبِّ زِدْنِي عِلْمًا',
    transliteration: "Rabbi zidni ilma",
    translation: 'My Lord, increase me in knowledge.',
    translationBn: 'হে আমার রব! আমার জ্ঞান বৃদ্ধি কর।',
    reference: 'Quran 20:114',
    icon: BookOpen,
  },
  {
    id: 90,
    category: 'general',
    categoryBn: 'সাধারণ',
    title: 'For Protection from Doubt',
    titleBn: 'সন্দেহ থেকে সুরক্ষা',
    arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الشَّكِّ وَالشِّرْكِ',
    transliteration: "Allahumma inni a'udhu bika minash-shakki wash-shirk",
    translation: 'O Allah, I seek refuge in You from doubt and polytheism.',
    translationBn: 'হে আল্লাহ! সন্দেহ ও শিরক থেকে তোমার কাছে আশ্রয় চাই।',
    reference: 'Abu Dawud',
    icon: Shield,
  },
  {
    id: 91,
    category: 'general',
    categoryBn: 'সাধারণ',
    title: 'For Ease in Affairs',
    titleBn: 'কাজে সহজতার জন্য',
    arabic: 'اللَّهُمَّ لَا سَهْلَ إِلَّا مَا جَعَلْتَهُ سَهْلًا، وَأَنْتَ تَجْعَلُ الْحَزْنَ إِذَا شِئْتَ سَهْلًا',
    transliteration: "Allahumma la sahla illa ma ja'altahu sahla, wa anta taj'alul-hazna idha shi'ta sahla",
    translation: 'O Allah, there is no ease except what You make easy, and You make difficulty easy if You wish.',
    translationBn: 'হে আল্লাহ! তুমি যা সহজ কর তা ছাড়া কিছুই সহজ নয় এবং তুমি চাইলে কঠিনকেও সহজ করে দাও।',
    reference: 'Ibn Hibban',
    icon: Heart,
  },
  {
    id: 92,
    category: 'general',
    categoryBn: 'সাধারণ',
    title: 'For Acceptance of Deeds',
    titleBn: 'আমল কবুলের জন্য',
    arabic: 'رَبَّنَا تَقَبَّلْ مِنَّا إِنَّكَ أَنْتَ السَّمِيعُ الْعَلِيمُ',
    transliteration: "Rabbana taqabbal minna innaka antas-samee'ul-aleem",
    translation: 'Our Lord, accept from us. Indeed, You are the Hearing, the Knowing.',
    translationBn: 'হে আমাদের রব! আমাদের থেকে কবুল কর। নিশ্চয়ই তুমি সর্বশ্রোতা, সর্বজ্ঞ।',
    reference: 'Quran 2:127',
    icon: Sparkles,
  },
  {
    id: 93,
    category: 'general',
    categoryBn: 'সাধারণ',
    title: 'For Good End',
    titleBn: 'উত্তম পরিসমাপ্তির জন্য',
    arabic: 'اللَّهُمَّ اجْعَلْ خَيْرَ عُمْرِي آخِرَهُ، وَخَيْرَ عَمَلِي خَوَاتِمَهُ',
    transliteration: "Allahummaj'al khayra umri akhirahu, wa khayra amali khawatimahu",
    translation: 'O Allah, make the best part of my life its end, and the best of my deeds their conclusion.',
    translationBn: 'হে আল্লাহ! আমার জীবনের শেষভাগকে সর্বোত্তম বানাও এবং আমার আমলের শেষ অংশ সর্বোত্তম বানাও।',
    reference: 'Hakim',
    icon: Heart,
  },
  {
    id: 94,
    category: 'general',
    categoryBn: 'সাধারণ',
    title: 'When Facing Difficulty',
    titleBn: 'কঠিন সময়ে',
    arabic: 'حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ',
    transliteration: "Hasbunallahu wa ni'mal-wakeel",
    translation: 'Sufficient for us is Allah, and He is the best Disposer of affairs.',
    translationBn: 'আল্লাহই আমাদের জন্য যথেষ্ট এবং তিনি সর্বোত্তম কর্মবিধায়ক।',
    reference: 'Quran 3:173',
    icon: Shield,
  },
  {
    id: 95,
    category: 'general',
    categoryBn: 'সাধারণ',
    title: 'For Unity',
    titleBn: 'ঐক্যের জন্য',
    arabic: 'اللَّهُمَّ أَلِّفْ بَيْنَ قُلُوبِنَا، وَأَصْلِحْ ذَاتَ بَيْنِنَا',
    transliteration: "Allahumma allif bayna quloobina, wa aslih dhata baynina",
    translation: 'O Allah, bring our hearts together and reconcile between us.',
    translationBn: 'হে আল্লাহ! আমাদের হৃদয়গুলো জুড়ে দাও এবং আমাদের মধ্যে মিলমিশ করে দাও।',
    reference: 'Abu Dawud',
    icon: Users,
  },
  {
    id: 96,
    category: 'general',
    categoryBn: 'সাধারণ',
    title: 'For Trust in Allah',
    titleBn: 'আল্লাহর উপর ভরসার জন্য',
    arabic: 'تَوَكَّلْتُ عَلَى اللَّهِ رَبِّي وَرَبِّكُمْ',
    transliteration: "Tawakkaltu alallahi rabbi wa rabbikum",
    translation: 'I have placed my trust in Allah, my Lord and your Lord.',
    translationBn: 'আমি আল্লাহর উপর ভরসা করেছি, আমার রব এবং তোমাদের রব।',
    reference: 'Quran 11:56',
    icon: Heart,
  },
  {
    id: 97,
    category: 'general',
    categoryBn: 'সাধারণ',
    title: 'For Remembrance of Death',
    titleBn: 'মৃত্যু স্মরণের জন্য',
    arabic: 'اللَّهُمَّ أَكْثِرْ ذِكْرِي لِلْمَوْتِ، وَجَوَازِ الصِّرَاطِ',
    transliteration: "Allahumma akthir dhikri lil-mawt, wa jawazis-sirat",
    translation: 'O Allah, increase my remembrance of death and crossing the bridge.',
    translationBn: 'হে আল্লাহ! মৃত্যুর স্মরণ এবং পুলসিরাত পার হওয়ার কথা বেশি বেশি স্মরণ করিয়ে দাও।',
    reference: 'Ibn Hibban',
    icon: Heart,
  },
  {
    id: 98,
    category: 'general',
    categoryBn: 'সাধারণ',
    title: 'For Barakah in Time',
    titleBn: 'সময়ে বরকতের জন্য',
    arabic: 'اللَّهُمَّ بَارِكْ لَنَا فِي أَوْقَاتِنَا',
    transliteration: "Allahumma barik lana fi awqatina",
    translation: 'O Allah, bless us in our times.',
    translationBn: 'হে আল্লাহ! আমাদের সময়ে বরকত দাও।',
    reference: 'Tabarani',
    icon: Clock,
  },
  {
    id: 99,
    category: 'general',
    categoryBn: 'সাধারণ',
    title: 'For Love of Allah',
    titleBn: 'আল্লাহর ভালোবাসার জন্য',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ حُبَّكَ، وَحُبَّ مَنْ يُحِبُّكَ، وَحُبَّ عَمَلٍ يُقَرِّبُنِي إِلَى حُبِّكَ',
    transliteration: "Allahumma inni as'aluka hubbak, wa hubba man yuhibbuk, wa hubba amalin yuqarribuni ila hubbik",
    translation: 'O Allah, I ask You for Your love, the love of those who love You, and the love of deeds that will bring me closer to Your love.',
    translationBn: 'হে আল্লাহ! আমি তোমার ভালোবাসা চাই, যারা তোমাকে ভালোবাসে তাদের ভালোবাসা চাই এবং যে আমল তোমার ভালোবাসার নিকটবর্তী করে সেই আমলের ভালোবাসা চাই।',
    reference: 'Tirmidhi',
    icon: Heart,
  },
  {
    id: 100,
    category: 'general',
    categoryBn: 'সাধারণ',
    title: 'Comprehensive Dua',
    titleBn: 'সর্বব্যাপী দোয়া',
    arabic: 'اللَّهُمَّ آتِنَا مِنْ لَدُنْكَ رَحْمَةً وَهَيِّئْ لَنَا مِنْ أَمْرِنَا رَشَدًا',
    transliteration: "Allahumma atina min ladunka rahmah wa hayyi' lana min amrina rashada",
    translation: 'Our Lord, grant us from Yourself mercy and prepare for us from our affair right guidance.',
    translationBn: 'হে আল্লাহ! তোমার পক্ষ থেকে আমাদের রহমত দাও এবং আমাদের কাজ সঠিকভাবে পরিচালনা কর।',
    reference: 'Quran 18:10',
    icon: Sparkles,
  },
];

export function getDuasByCategory(categoryId: string): DuaItem[] {
  if (categoryId === 'all') return duas;
  return duas.filter(dua => dua.category === categoryId);
}

export function getCategoryColor(categoryId: string): string {
  const category = duaCategories.find(c => c.id === categoryId);
  return category?.color || 'bg-primary/10 text-primary';
}
